services:
  postgres:
    image: toleg/postgres_fdw
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./sql/postgres_all_setup.sql:/docker-entrypoint-initdb.d/postgres_all_setup.sql

