services:
  # this is obsolete image. TODO: switch to official Oracle images
  oracle:
    image: store/oracle/database-enterprise:12.2.0.1
    environment:
      # default "sys" user password mentioned in oracle image readme
      SYS_PASSWORD: Oradoc_db1
    ports:
      - 1521:1521
    volumes:
      # this startup script is for postgres image and is not picked up by oracle
      #- ./oracle_setup.sql:/docker-entrypoint-initdb.d/oracle_setup.sql

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql_setup.sql:/docker-entrypoint-initdb.d/mysql_setup.sql

  postgres:
    image: toleg/postgres_fdw
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./fdw_setup.sql:/docker-entrypoint-initdb.d/fdw_setup.sql
    depends_on:
      - oracle
      - mysql

