services:
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: om_oracle
    environment:
      ORACLE_PWD: admin   # password for SYS, SYSTEM and PDBADMIN
    ports:
      - 1521:1521   # JDBC
      - 5500:5500   # Enterprise Manager GUI
    volumes:
      - ./oracle_setup.sql:/docker-entrypoint-initdb.d/startup/oracle_setup.sql

  mysql:
    image: mysql
    container_name: om_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - ./mysql_setup.sql:/docker-entrypoint-initdb.d/mysql_setup.sql

  datero:
    image: docker.io.chumaky/datero_engine
    container_name: om_datero
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ../import_schema.sql:/docker-entrypoint-initdb.d/admin.sql
      - ./fdw_setup.sql:/docker-entrypoint-initdb.d/fdw_setup.sql
    depends_on:
      - oracle
      - mysql

