# default postgres version which will be used if no version is specified
default_version: 15

# list of individual FDW versions for corresponding postgres version
# if version is not in SemVer format, then it will be treated as a branch name
16:
  pg_base: 16.2
  fdw:
    mysql: 2.9.1
    oracle: 2.6.0
    sqlite: 2.4.0
    mongo: 5.5.1
    mssql: master

15:
  pg_base: 15.2
  fdw:
    mysql: 2.9.0
    oracle: 2.5.0
    sqlite: 2.3.0
    mongo: 5.5.0
    mssql: 2.0.3

14:
  pg_base: 14.4
  fdw:
    mysql: 2.8.0
    oracle: 2.4.0
    sqlite: 2.1.1
    mongo: 5.4.0
    mssql: 2.0.2


# fdw github repositories
fdw:
  root:
    mysql: https://github.com/EnterpriseDB/mysql_fdw/archive/refs/
    oracle: https://github.com/laurenz/oracle_fdw/archive/refs/
    sqlite: https://github.com/pgspider/sqlite_fdw/archive/refs/
    mongo: https://github.com/EnterpriseDB/mongo_fdw/archive/refs/
    mssql: https://github.com/tds-fdw/tds_fdw/archive/refs/
  release:
    mysql: tags/REL-${major}_${minor}_${patch}.zip
    oracle: tags/ORACLE_FDW_${major}_${minor}_${patch}.zip
    sqlite: tags/v${major}.${minor}.${patch}.zip
    mongo: tags/REL-${major}_${minor}_${patch}.zip
    mssql: tags/v${major}.${minor}.${patch}.zip
  branch:
    mysql: heads/${branch}.zip
    oracle: heads/${branch}.zip
    sqlite: heads/${branch}.zip
    mongo: heads/${branch}.zip
    mssql: heads/${branch}.zip
