services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mm_mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: mssql_2019
    ports:
      - 1433:1433

  # temp container to populate seed data within "mssql" container.
  mssql_init:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mm_mssql_init
    volumes:
      - ./mssql_setup.sh:/docker-entrypoint-initdb.d/mssql_setup.sh
      - ./mssql_setup.sql:/docker-entrypoint-initdb.d/mssql_setup.sql
    working_dir: "/docker-entrypoint-initdb.d"
    command:  [ "./mssql_setup.sh" ]
    depends_on: mssql

  mongo:
    image: mongo
    container_name: mm_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    volumes:
      - ./mongo_setup.js:/docker-entrypoint-initdb.d/mongo_setup.js

  postgres:
    image: toleg/postgres_fdw
    container_name: mm_postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ../admin.sql:/docker-entrypoint-initdb.d/admin.sql
      - ./fdw_setup.sql:/docker-entrypoint-initdb.d/fdw_setup.sql
    depends_on:
      - mssql_init
      - mongo
